[profile.default]
src     = "."
out     = "out"
libs    = ["lib"]
test    = "test"
script  = "script"
solc    = "0.8.26"
optimizer       = true
optimizer_runs  = 1_000_000
via_ir          = true

# Sepolia fork — set ETH_RPC_URL in .env before running tests
[rpc_endpoints]
sepolia = "${ETH_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = "sepolia" }
